kind: ConfigMap
apiVersion: v1
metadata:
 name: nginx-ingress-controller
 namespace: nginx-ingress
data:
  map-hash-bucket-size: "64"
  use-forwarded-headers: "true"
  access-log-path: "/nginx-ingress-logs-1/access.log"
  error-log-path: "/nginx-ingress-logs-1/error.log"
  log-format-escape-json: "true"
  log-format-upstream: '{"time": "$time_iso8601",
        "remote_addr": "$proxy_protocol_addr",
        "x-forward-for": "$proxy_add_x_forwarded_for"
        "method": "$request_method",
        "path": "$uri",
        "status": $status,
        "request_time": $request_time,
        "body_bytes_sent": $body_bytes_sent,
        "request_length": $request_length,
        "upstream_addr": "$upstream_addr",
        "upstream_response_length": $upstream_response_length,
        "upstream_response_time": $upstream_response_time,
        "upstream_status": $upstream_status,
        "http_referrer": "$http_referer",
        "remote_user": "$remote_user",
        "http_user_agent": "$http_user_agent",
        "proxy_upstream_name":"$proxy_upstream_name",
        "$proxy_alternative_upstream_name": "$proxy_alternative_upstream_name",
        "request_id": "$req_id"
        }'
