kind: ConfigMap
apiVersion: v1
metadata:
 name: nginx-ingress-controller
 namespace: nginx-ingress
data:
  map-hash-bucket-size: "64"
  proxy-body-size: "1024m"
  client-header-buffer-size: "16k"
  large-client-header-buffers: "4 32k"
  server-tokens: "false"
  use-gzip: "true"
  gzip-level: "2"
  gzip-min-length: "1024"
  max-worker-connections: "65535"
  use-forwarded-headers: "true"
